# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UaVpb65CovtbkW-41krHaSf-LR8Ms5Z
"""

from sklearn.datasets import load_iris
from sklearn.cluster import AgglomerativeClustering
import numpy as np
import pandas as pd
import matplotlib as plt
from matplotlib import pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
import pickle
import matplotlib.dates as md
import datetime as dt
import torch
import torch.nn as nn
import seaborn as sns
import time
from fastai.vision.all import load_learner
import sys
from sklearn.metrics import accuracy_score, roc_auc_score
import os
from flask import Flask, request
from sklearn.preprocessing import MinMaxScaler
import csv
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.linear_model import LinearRegression
import numpy as np

df = pd.read_csv('exchange_rates[1].csv')
df.head(120)

df.shape

df_train, df_test = train_test_split(df, test_size=0.2, random_state=0)

x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 10, 15, 20, 25, 30])

model = LinearRegression()
model.fit(x, y)
model = LinearRegression().fit(x, y)
model.score(x, y)

model.fit(x,y)

import matplotlib.pyplot as plt

plt.xlabel('currency')

plt.plot(x, model.predict(x),color ='red')

plt.ylabel('price')
plt.scatter(x, y)

model.predict([[10]])